# DigitalOcean App Platform Configuration - GitHub Integration
name: intelligent-hotel-scraper
static_sites: []
services:
- name: api
  source_dir: /
  github:
    repo: noahsawyer97/hotel-scraper-intelligent
    branch: main
  run_command: gunicorn --bind 0.0.0.0:8080 app:app
  environment_slug: python
  instance_count: 1
  instance_size_slug: professional-s  # Upgraded for more disk space and memory
  http_port: 8080
  envs:
  - key: FLASK_ENV
    value: production
  - key: SCRAPE_TIMEOUT
    value: "60"
  - key: MAX_RETRIES
    value: "3"
  - key: HEADLESS_BROWSER
    value: "true"
  - key: OUTPUT_DIR
    value: "scraped_data"
  - key: USE_FREE_AI
    value: "false"
  - key: USE_OPENAI_API
    value: "true"
  - key: OPENAI_API_KEY
    scope: RUN_TIME
    type: SECRET
